### ISSUE TITLE
有关安卓手机支付宝扫码页面无法输入金额的bug

### ISSUE THREAD

**Issue by hiboyluo** [helicopters/wc-keyboard#1]
你好，用安卓手机支付宝扫码打开页面后，无法输入金额

**Comment by helicopters** [comment]
hi, 能留个微信给我吗，或者详细描述下问题.

**Comment by helicopters** [comment]
@hiboyluo hi, 能留个微信给我, 或者详细描述下问题.

**Comment by hiboyluo** [comment]
恩。微信号是791044994.我用手机支付宝扫码打开页面后（安卓手机），点击数字键盘后，输入框中没有输入金额。用苹果手机测试，没有发现这个问题，不知道什么原因
